name: Generate Hexo pages

on: [push]

permissions:
  write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          path: website
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Build
        working-directory: website
        run: |
          git submodule update --init
          npx hexo clean
          npx hexo generate
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with: 
          path: website/public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
  comment:
    needs: deploy
    permissions:
      write-all
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Call blog actions
        run: |
          git clone https://github.com/Bot-wxt1221/blog.git blog
          cd blog
          echo 1 > genshin.txt
          rm -rf genshin.txt
          date > genshin.txt
          git add .
          git commit -m "Generate comments"
          git push
