name: Generate Hexo pages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          path: website
          fetch-depth: 0
      - name: Install nodejs
        working-directory: website
        run: |
          sudo apt install nodejs npm
        
      - name: Build
      	working-directory:website
        run: |
          npx hexo deploy

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
       	with:
          path: website/public
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      needs: build
      runs-on: ubuntu-latest
      name: Deploy
      steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
